name: SimpleClearChat
version: 1.0.0
main: DerCommander610\Clear\Main
api: [4.19.3]
author: DerCommander610

commands:
  clearchat:
    description: "Leere den chat mit diesen command!"
    permission: clearchat.cmd
permissions:
   clearchat.cmd:
    default: op    
