name: SimpleClearChat
version: 1.0.0
main: DerCommander610\Clear\Main
api: [4.19.3]
author: DerCommander610

commands:
  clearchat:
    description: "Clear the Chat!"
    permission: simpleclearchat.clearchat.cmd
permissions:
   simpleclearchat.clearchat.cmd:
    default: op    
